"""Initial migration

Revision ID: a25d4cf66fdf
Revises: 
Create Date: 2023-06-12 10:14:13.086158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a25d4cf66fdf"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hour", sa.String(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("market_data")
    # ### end Alembic commands ###
