"""Add date column to market_data table

Revision ID: b3d4872c339d
Revises: a25d4cf66fdf
Create Date: 2023-06-12 10:36:30.086735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b3d4872c339d"
down_revision = "a25d4cf66fdf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("market_data", schema=None) as batch_op:
        batch_op.add_column(sa.Column("date", sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("market_data", schema=None) as batch_op:
        batch_op.drop_column("date")

    # ### end Alembic commands ###
